### ISSUE TITLE
Multijob.finished() never returns True

### ISSUE THREAD

**Issue by stepenta** [fp7mplane/protocol-ri#25]

**Comment by MKV21** [comment]
https://github.com/fp7mplane/protocol-ri/blob/sdk/mplane/scheduler.py#L303

This returns True if all jobs have been scheduled and there are no jobs running. The later could be a problem because at the moment jobs are only removed from the jobs list if _collect_results was called (done in get_reply). If this is a problem I can add a _collect_results() call in finished.

**Comment by stepenta** [comment]
In some cases it could be a problem, since one could wait for job.finished() before trying to get the reply, like in my case. I don't like the _collect_results() call in finished, since it should return some data instead of a boolean value. Maybe just specify in the description that if there are results pending, it will return false.
What do you think?

**Comment by stepenta** [comment]
solved by adding a more precise description in the comment of the funcion
