### ISSUE TITLE
client running capability with when, but it gets executed only once

### ISSUE THREAD

**Issue by mdusi** [fp7mplane/protocol-ri#58]
Issuing a 'invoke_capability(cap.get_token(), when, params, None)' from a client (not extending the Cmd.cmd class as in mpcli) causes the supervisor to execute the capability only once, regardless of the value of 'when' (e.g., even if when = now + 10s / 1s). Is this the expected behavior?

**Comment by britram** [comment]
Yes. The scheduler will only cause the associated mplane.scheduler.Job to run once (since a periodic temporal scope as given in the example will result in a single mplane.model.Result). It is up to the mplane.scheduler.Service subclass to properly implement handling of the period in its run() method (see the ping component for an illustration).

**Comment by mdusi** [comment]
oh ok, it makes sense, thanks!
