### ISSUE TITLE
Client does not recognize the same capability offered by more than one component

### ISSUE THREAD

**Issue by ali-safari** [fp7mplane/protocol-ri#60]
We have some Tstat proxies which offer the same set of capabilities but the client sees only the capabilities offer by the first connected component and I checked the output on supervisor. It seems that two set of capabilities have the same token value.  (The components have different certificate and DN ). 

The Supervisor prints:
ListenerHttpComponent running on port 8890
Added \<Service for \<capability: measure (tstat-exporter_streaming) when now ... future token f669c3cc schema 23f9af9a p/m/r 4/3/0>>
Added \<Service for \<capability: measure (tstat-exporter_log) when past ... future token eb1e0c4f schema 9baaae2e p/m/r 1/3/0>>
Added \<Service for \<capability: measure (tstat-log_tcp_complete-tcp_options) when now ... future token 68cc4936 schema 62657c35 p/m/r 0/3/46>>
Added \<Service for \<capability: measure (tstat-log_tcp_complete-core) when now ... future token 7ee0a281 schema 39952155 p/m/r 0/3/42>>
Added \<Service for \<capability: measure (tstat-log_tcp_complete-end_to_end) when now ... future token 1ab5668d schema ce6233ed p/m/r 0/3/7>>
Added \<Service for \<capability: measure (tstat-log_tcp_complete-layer7) when now ... future token c03c028d schema c445bac9 p/m/r 0/3/4>>
Added \<Service for \<capability: measure (tstat-log_rrds) when now ... future token f0bab5b4 schema 3231d66d p/m/r 0/3/9>>
Added \<Service for \<capability: measure (tstat-log_http_complete) when now ... future token d8c8fa10 schema d2deb3c1 p/m/r 0/3/17>>
Added \<Service for \<capability: measure (tstat-exporter_rrd) when past ... future token 58d1109f schema 1216bc3b p/m/r 1/3/3>>
Added \<Service for \<capability: measure (tstat-log_tcp_complete-p2p_stats) when now ... future token 9963ddd3 schema 348428a8 p/m/r 0/3/6>> 
Added \<Service for \<capability: measure (callback) when now ... future token 8fd14712 schema b8f9fb5f p/m/r 0/0/0>>
Added \<Service for \<capability: measure (repository-collect_streaming) when now ... future token 95145df5 schema 9baaae2e p/m/r 1/3/0>>
Added \<Service for \<capability: measure (repository-collect_rrd) when past ... future token 995e6991 schema 1216bc3b p/m/r 1/3/3>>
Added \<Service for \<capability: measure (repository-collect_log) when past ... future token d7495694 schema 9baaae2e p/m/r 1/3/0>>
Added \<Service for \<capability: measure (callback) when now ... future token 8fd14712 schema b8f9fb5f p/m/r 0/0/0>>
Added \<Service for \<capability: measure (tstat-log_tcp_complete-end_to_end) when now ... future token 1ab5668d schema ce6233ed p/m/r 0/3/7>>
Added \<Service for \<capability: measure (tstat-log_tcp_complete-p2p_stats) when now ... future token 9963ddd3 schema 348428a8 p/m/r 0/3/6>> 
Added \<Service for \<capability: measure (tstat-log_tcp_complete-core) when now ... future token 7ee0a281 schema 39952155 p/m/r 0/3/42>>
Added \<Service for \<capability: measure (tstat-log_http_complete) when now ... future token d8c8fa10 schema d2deb3c1 p/m/r 0/3/17>>
Added \<Service for \<capability: measure (tstat-exporter_log) when past ... future token eb1e0c4f schema 9baaae2e p/m/r 1/3/0>>
Added \<Service for \<capability: measure (tstat-log_rrds) when now ... future token f0bab5b4 schema 3231d66d p/m/r 0/3/9>>
Added \<Service for \<capability: measure (tstat-exporter_rrd) when past ... future token 58d1109f schema 1216bc3b p/m/r 1/3/3>>
Added \<Service for \<capability: measure (tstat-exporter_streaming) when now ... future token f669c3cc schema 23f9af9a p/m/r 4/3/0>>
Added \<Service for \<capability: measure (tstat-log_tcp_complete-tcp_options) when now ... future token 68cc4936 schema 62657c35 p/m/r 0/3/46>>
Added \<Service for \<capability: measure (tstat-log_tcp_complete-layer7) when now ... future token c03c028d schema c445bac9 p/m/r 0/3/4>>
Added \<Service for \<capability: measure (callback) when now ... future token 8fd14712 schema b8f9fb5f p/m/r 0/0/0>>

**Comment by britram** [comment]
This is intentional.

The capabilities offered by different observation points should have different fixed parameter constraints or metadata describing the observation point (which networks/interfaces are covered). If there is no data level difference between the capabilities at all, they are indeed the same capability, and it does not matter who provides it.

**Comment by ali-safari** [comment]
I checked with two components with different metadata (different token generated for capability) but the supervisor and the client are based on the label rather then token. for instance in Supervisor.py in lines 144, 145 and 168 instead of get_token() we have  self._caps.append([msg.get_label(), identity])
and in client listcap and so forth.

**Comment by stepenta** [comment]
Those bugs in client and supervisor are easily fixed. 
The real problem is that when the supervisor (more precisely, its component.py part) receives a specification from the client, it looks for a match in its capabilities through the fulfills() function (https://github.com/fp7mplane/protocol-ri/blob/sdk/mplane/scheduler.py#L443). 
This function is based on _schema_hash in model.py (https://github.com/fp7mplane/protocol-ri/blob/sdk/mplane/model.py#L2298), that takes into account parameters and result columns.
But since the only difference in the schemas of two tstat capabilities is in the metadata, it cannot distinguish between the two.
Brian, what do you think about this? Should we add a control on metadata somewhere? 
Maybe in submit_job() (https://github.com/fp7mplane/protocol-ri/blob/sdk/mplane/scheduler.py#L434), or in fulfills() (https://github.com/fp7mplane/protocol-ri/blob/sdk/mplane/model.py#L2593), or in _schema_hash() (https://github.com/fp7mplane/protocol-ri/blob/sdk/mplane/model.py#L2298)?

**Comment by britram** [comment]
Ah, indeed.

Change the capability to have different identification of the observation points as a parameter with a single-value constraint. And while you're at it, change the label too (it'll be easier to see the difference in the UIs, which have labels plastered all over the place).

The intention in the architecture is that these identifiers be parameters with single value constraints, not metadata. I wouldn't go hacking metadata checks into the identity at this point.

**Comment by stepenta** [comment]
But the hash of the statement computed in _schema_hash() is only based on:
self._params.keys()
self._resultcolumns.keys()

Adding a one-value parameter (with a different value for each probe, but still same key) or changing the label will not change the hash, am I wrong?

**Comment by britram** [comment]
Hm, that's a good point.

There are two kinds of equality here: schema (does this have the same data type) and capability (are these the same measurement). Are we matching n schema when we should not be here?

(The pervasive use of labels everywhere confuses all of this, but we knew that was going to happen when we stuck labels everywhere...)

**Comment by britram** [comment]
Or, in more concrete terms, is this something that can be fixed by replacing a call to `_schema_hash()` (or something that call it) with a call to `_mpcv_hash()` (which includes metadata as well as constraints)? This was written for statements as opposed to capabilities, so it might need a hack to drop `spv` for capabilities (which have no values)

**Comment by britram** [comment]
I have reviewed this in more detail. 

## On the client side

According to the code, Capability tokens are already based on `_mpcv_hash()`, (`_default_token()` at mplane/model.py:2378, not overridden — meaning that as long as the capabilities differ in single-value constraints or metadata (which, representing different passive measurement instances, they must), the client will treat them as different. Unfortunately, the decision to key everything at clients according to label _or_ token means that even if the tokens don't collide the labels might. It is up to capability developers to make sure labels don't collide; BaseClient's `capability_labels()` is written in such a way that last label inserted wins. The only fix is to name things uniquely and descriptively (which we should all be doing anyway. :) )

## On the supervisor side

In general, this seems like a consequence of using a debugging hack (passthrough supervisor) in anything other than a debugging context: according to the architecture the supervisor should have application-specific logic for composition and decomposition, so should never be in a position to have two capabilities that match in this way.

But this is what we have. So let me propose a 

## Solution

All capabilities need to be differentiable by parameter constraints (for tstat, the address of the interface on which observations take place needs to be exposed as a single-value constraint). 

`fulfills()` should additionally check whether a specification's values might fit the capability's constraints. Not considering metadata for `fulfills()` is correct — metadata should be used in analysis, not by the component/supervisor to determine what matches, because making that determination is metadata- (and situation-)specific.

**Comment by britram** [comment]
@stepenta, @ali-safari: try 37fb620f5240d7b30a7ca4f7040e464b183d1eab

**Comment by stepenta** [comment]
Thanks, that worked. Some minor tweaks were needed also in client and supervisor, but now it's ok.
